// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SmeBr_8xxF6uEPW0poD3MVnQjidyhlU',
    appId: '1:313324283065:web:2a31801d76d6a8db4ee768',
    messagingSenderId: '313324283065',
    projectId: 'chat-app-61ffe',
    authDomain: 'chat-app-61ffe.firebaseapp.com',
    storageBucket: 'chat-app-61ffe.appspot.com',
    measurementId: 'G-BDLL7NNZ20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzSDWo6_vlBhZvC6mXdvKM_z2iSTlRmc',
    appId: '1:313324283065:android:d2f0698cf8c4d79a4ee768',
    messagingSenderId: '313324283065',
    projectId: 'chat-app-61ffe',
    storageBucket: 'chat-app-61ffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX_Q3RmYDiSodn47YErP-1jgHMWyyGnOc',
    appId: '1:313324283065:ios:146503747490a25b4ee768',
    messagingSenderId: '313324283065',
    projectId: 'chat-app-61ffe',
    storageBucket: 'chat-app-61ffe.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX_Q3RmYDiSodn47YErP-1jgHMWyyGnOc',
    appId: '1:313324283065:ios:6652e55da7badac04ee768',
    messagingSenderId: '313324283065',
    projectId: 'chat-app-61ffe',
    storageBucket: 'chat-app-61ffe.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
